  - name: apt update
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400

  - name: instala requisitos basicos
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - software-properties-common
        - containerd
        - certbot
      state: latest

  - name: adiciona chave docker
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present

  - name: adiciona repositorio docker
    apt_repository:
      repo: deb https://download.docker.com/linux/debian bullseye stable
      state: present

  - name: instala docker
    apt:
      name: docker-ce
      state: latest

  - name: instala docker-compose
    get_url: 
      url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'

  - name: cria diretorio rc
    file:
      path: /usr/local/rocketchat
      state: directory

  - name: cria certificado
    shell: "certbot certonly --cert-name {{ dns }} -d {{ dns }} --email suporte@confirmationcall.com.br --noninteractive --standalone --agree-tos"

  - name: cria renovação de certificado
    cron:
      name: "certificado"
      state: present
      minute: "40"
      hour: "23"
      day: "25"
      month: "*"
      weekday: "*"
      job: "certbot certonly --cert-name {{ dns }} -d {{ dns }} --email suporte@confirmationcall.com.br --noninteractive --standalone --agree-tos"

  - name: envia arquivo nginx.conf
    template:
      src: ../templates/nginx.j2
      dest: /usr/local/rocketchat/nginx.conf

  